FROM oven/bun:1

WORKDIR /ws-backend


COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./apps/ws-server ./apps/ws-server



RUN bun install 

RUN bun run db:generate

EXPOSE 8081

CMD [ "bun","run","start:websocket" ]